slice_name: Chicago Snowfall by Month (in.)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 25__table
  viz_type: echarts_timeseries_line
  slice_id: 123
  x_axis: month
  xAxisForceCategorical: true
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: snowfall_sum
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 769
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(snowfall_sum)
    optionName: metric_8v0fxn0zxnh_y0rmb4b2rmp
    sqlExpression: null
  groupby:
  - year
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_hrpwcin75lu_7hazd1o7jdn
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: date
  - clause: WHERE
    comparator:
    - 1
    - 2
    - 4
    - 3
    - 10
    - 11
    - 12
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_i2yvb01nyha_cq6yz30egxa
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: month
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category20
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: false
  showTooltipPercentage: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":25,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"month","op":"IN","val":[1,2,4,3,10,11,12]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"month","label":"month","expressionType":"SQL"},"year"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"snowfall_sum","description":null,"expression":null,"filterable":true,"groupby":true,"id":769,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(snowfall_sum)","optionName":"metric_8v0fxn0zxnh_y0rmb4b2rmp","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"snowfall_sum","description":null,"expression":null,"filterable":true,"groupby":true,"id":769,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(snowfall_sum)","optionName":"metric_8v0fxn0zxnh_y0rmb4b2rmp","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["year"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["month"],"columns":["year"],"aggregates":{"SUM(snowfall_sum)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(snowfall_sum)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"25__table","viz_type":"echarts_timeseries_line","slice_id":123,"x_axis":"month","xAxisForceCategorical":true,"x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"snowfall_sum","description":null,"expression":null,"filterable":true,"groupby":true,"id":769,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(snowfall_sum)","optionName":"metric_8v0fxn0zxnh_y0rmb4b2rmp","sqlExpression":null}],"groupby":["year"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_hrpwcin75lu_7hazd1o7jdn","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"date"},{"clause":"WHERE","comparator":[1,2,4,3,10,11,12],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_i2yvb01nyha_cq6yz30egxa","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"month"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"d3Category20","seriesType":"line","only_total":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":false,"showTooltipPercentage":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 4f5f33b9-19ad-408b-ae88-6465279f139a
version: 1.0.0
dataset_uuid: f4ad06c2-a5ef-4b03-b1d9-e9871e6cb81c
